version: '3.3'
services:
  postgres:
    image: library/postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    restart: always
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.com
      PGADMIN_DEFAULT_PASSWORD: xxx
    depends_on:
      - postgres
    networks:
      - pg-net

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-net: